# 코틀린에서 예외를 다루는 방법

인프런에서 `최태원 지식 공유자`님의   
`자바 개발자를 위한 코틀린 입문`을 수강하며  정리한 내용 입니다.  
하단에 강의 링크 있습니다.

## try catch finally 구문

예) 주어진 문자열을 정수로 변경하는 예제

```kotlin
fun parseIntOrThrow(str: String): Int {
    try {
        return str.toInt()
    } catch (e: NumberFormatException) {
        throw IllegalArgumentException("${str}은 숫자가 아닙니다.")
    }
}
```

- 타입이 뒤에 위치
- new를 사용하지 않음
- 포맷팅이 간결

예) 주어진 문자열을 정수로 변경하는 예제, 실패하면 null 리턴

```kotlin
fun parseIntOrThrowNull(str: String): Int? {
    return try {
        str.toInt()
    } catch (ne: NumberFormatException) {
        null
    }
}
```

→ try-catch도 하나의 `Expression` 이다.

→ try catch finally 역시 동일

## Checked Exception과 Unchecked Exception

예) 프로젝트 내 파일의 내용물을 읽어오는 예제

```kotlin
class FilePrinter {
    fun readFile() {
        val currentFile = File(".")
        val file = File(currentFile.absolutePath + "/a.txt")
        val reader = BufferedReader(FileReader(file))
        println(reader.readLine())
        reader.close()
    }
}
```

- 자바에서 파일관련 IOException이라는 Checked Exception으로 인해서 명시적으로 표현했는데 코틀린에서는 굳이 throws를 명시하지 않아도 빨간줄이 뜨지 않는다.
- 즉, 코틀린에는 throws 구문이 없다.
- `코틀린`에서는 `checked Exception`과 `unchecked exception`을 구분하지 않는다. 모두 `unchecked exception`이다.

## try with resources

🤠 **코틀린에는 try with resources라는 구문이 없다.**

```kotlin
class FilePrinter {
    fun readFile(path: String) {
       BufferedReader(FileReader(path)).use { reader ->
           println(reader.readLine())
       }
    }
}
```

→ 대신 use 라는 `inline 확장함수`를 사용해야 한다.

Reference:  
[자바 개발자를 위한 코틀린 입문](https://www.inflearn.com/course/java-to-kotlin/dashboard)